services:
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api-gateway:
    image: api-gateway
    build:
      context: ../../ApiGateway
    ports:
      - 8765:8765
  blob-store-service:
    image: blob-store-service
    build:
      context: ../../blob_store_service
    ports:
      - 6543:6543
  discovery-server:
    image: discovery-server
    build:
      context: ../../DiscoveryServer
    ports:
      - 8761:8761
  friend-service:
    image: friend-service
    build:
      context: ../../friend_service
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://mongo/user
      - KAFKA_CLIENT_HOST=kafka:29092
      - USER_SERVICE_GRPC_ADDRESS=user-service:50051
  message-service:
    image: message-service
    build:
      context: ../../message_service
    ports:
      - 3003:3003
    environment:
      - MONGODB_URI=mongodb://mongo/message
      - KAFKA_CLIENT_HOST=kafka:29092
      - EUREKA_DISCOVERY_SERVER_HOST=discovery-server
      - USER_SERVICE_GRPC_ADDRESS=user-service:50051
      
  notification-service:
    image: notification-service
    build:
      context: ../../notification_service
    ports:
      - 3002:3002
    environment:
      - MONGODB_URI=mongodb://mongo/notification
      - KAFKA_CLIENT_HOST=kafka:29092
      - EUREKA_DISCOVERY_SERVER_HOST=discovery-server
      
  socket-gateway:
    image: socket-gateway
    build:
      context: ../../socket_gateway
    ports:
      - 3004:3004
    environment:
      - KAFKA_CLIENT_HOST=kafka:29092
      - EUREKA_DISCOVERY_SERVER_HOST=discovery-server
  user-service:
    image: user-service
    build:
      context: ../../user_service
    ports:
      - 3000:3000
      - 50051:50051
    environment:
      - MONGODB_URI=mongodb://mongo/user
      - KAFKA_CLIENT_HOST=kafka:29092
      - EUREKA_DISCOVERY_SERVER_HOST=discovery-server