services:
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - social-media-network
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: goddie9x
      MONGO_INITDB_ROOT_PASSWORD: thisIsJustTheTestPassword123
    networks:
      - social-media-network
  oracle:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=thisIsJustTheTestPassword123
      - ORACLE_USER=goddie9x
    ports:
      - "1521:1521" 
    networks:
    - social-media-network

  api-gateway:
    image: api-gateway
    build:
      context: ../../ApiGateway
    ports:
      - 8765:8765
    depends_on:
      - discovery-server
    networks:
      - social-media-network

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisIsJustTheTestPassword123
    networks:
      - social-media-network

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_DISABLE_DEFAULT_USER="true"
    networks:
      - social-media-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=thisIsJustTheTestPassword123
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      - social-media-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    ports:
      - 5601:5601
    networks:
      - social-media-network
  blob-store-service:
    image: blob-store-service
    build:
      context: ../../blob_store_service
    ports:
      - 6543:6543
    depends_on:
      - postgres
      - discovery-server
      - api-gateway
    networks:
      - social-media-network
  post-service:
    image: post-service
    build:
      context: ../../post_service
    ports:
      - 3005:3005
    depends_on:
      - oracle
      - discovery-server
      - api-gateway
    networks:
      - social-media-network
  discovery-server:
    image: discovery-server
    build:
      context: ../../DiscoveryServer
    ports:
      - 8761:8761
    networks:
      - social-media-network

  friend-service:
    image: friend-service
    build:
      context: ../../friend_service
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - discovery-server
      - api-gateway
    networks:
      - social-media-network

  message-service:
    image: message-service
    build:
      context: ../../message_service
    ports:
      - 3003:3003
    depends_on:
      - mongo
      - discovery-server
      - api-gateway
    networks:
      - social-media-network
      
  notification-service:
    image: notification-service
    build:
      context: ../../notification_service
    ports:
      - 3002:3002
    depends_on:
      - mongo
      - discovery-server
      - api-gateway
    networks:
      - social-media-network
      
  socket-gateway:
    image: socket-gateway
    build:
      context: ../../socket_gateway
    ports:
      - 3004:3004
    depends_on:
      - mongo
      - discovery-server
      - api-gateway
    networks:
      - social-media-network

  user-service:
    image: user-service
    build:
      context: ../../user_service
    ports:
      - 3000:3000
      - 50051:50051
    depends_on:
      - mongo
      - discovery-server
      - api-gateway
    networks:
      - social-media-network

networks:
  social-media-network:
    driver: bridge